tap "daipeihust/tap"
tap "dash2701/dash2701"
tap "homebrew/bundle"
tap "homebrew/services"
tap "koekeishiya/formulae"
tap "modularml/packages"
# ChatGPT cli
brew "aichat"
# New file format for still image compression
brew "jpeg-xl"
# Codec library for encoding and decoding AV1 video streams
brew "aom"
# Opinionated way of installing Argo CD and managing GitOps repositories
brew "argocd-autopilot"
# Platform built on V8 to build network applications
brew "node"
# Secure and free password manager for all of your devices
brew "bitwarden-cli"
# OCR (Optical Character Recognition) engine
brew "tesseract"
# Play, record, convert, and stream audio and video
brew "ffmpeg"
# WebDriver <-> Marionette proxy
brew "geckodriver"
# Open source suite of directory software
brew "openldap"
# Passphrase entry dialog utilizing the Assuan protocol
brew "pinentry"
# GNU Pretty Good Privacy (PGP) package
brew "gnupg"
# Like cURL, but for gRPC
brew "grpcurl"
# Improved top (interactive process viewer)
brew "htop"
# Lightweight and flexible command-line JSON processor
brew "jq"
# User-friendly front-end to ssh-agent(1)
brew "keychain"
# Template-free customization of Kubernetes YAML manifests
brew "kustomize"
# Simple terminal UI for git commands
brew "lazygit"
# Run a Kubernetes cluster locally
brew "minikube"
# 'traceroute' and 'ping' in a single tool
brew "mtr"
# Ambitious Vim-fork focused on extensibility and agility
brew "neovim"
# OpenBSD freely-licensed SSH connectivity tools
brew "openssh"
# Shell command parallelization utility
brew "parallel"
# Search tool like grep and The Silver Searcher
brew "ripgrep"
# Command-line tool for the Amazon S3 service
brew "s3cmd"
# Organize software neatly under a single directory tree (e.g. /usr/local)
brew "stow"
# Terminal multiplexer
brew "tmux"
# Display directories as trees (with optional color/HTML output)
brew "tree"
# Executes a program periodically, showing output fullscreen
brew "watch"
# Shell extension to navigate your filesystem faster
brew "zoxide"
# Switch your input method through terminal
brew "daipeihust/tap/im-select"
brew "dash2701/dash2701/chatgptdash"
# A tiling window manager for macOS based on binary space partitioning.
brew "koekeishiya/formulae/yabai"
# Modular developer CLI tool
brew "modularml/packages/modular"
# Automated testing of webapps for Google Chrome
cask "chromedriver"
# Tool to hide status bar icons
cask "dozer"
# Productivity app
cask "dropzone"
# Keyboard customizer
cask "karabiner-elements"
# GPU-based terminal emulator
cask "kitty"
