after-login-command = []
after-startup-command = []

start-at-login = true

# Normalizations. See: https://nikitabobko.github.io/AeroSpace/guide#normalization
enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true

accordion-padding = 30

default-root-container-layout = 'tiles'
default-root-container-orientation = 'auto'

on-focused-monitor-changed = ['move-mouse monitor-lazy-center']

automatically-unhide-macos-hidden-apps = true

non-empty-workspaces-root-containers-layout-on-startup = 'smart'

[key-mapping]
    preset = 'qwerty'

[gaps]
    inner.horizontal = 5
    inner.vertical =   5
    outer.left =       5
    outer.bottom =     5
    outer.top =        5
    outer.right =      5

[mode.main.binding]

    # All possible keys:
    # - Letters.        a, b, c, ..., z
    # - Numbers.        0, 1, 2, ..., 9
    # - Keypad numbers. keypad0, keypad1, keypad2, ..., keypad9
    # - F-keys.         f1, f2, ..., f20
    # - Special keys.   minus, equal, period, comma, slash, backslash, quote, semicolon,
    #                   backtick, leftSquareBracket, rightSquareBracket, space, enter, esc,
    #                   backspace, tab, pageUp, pageDown, home, end, forwardDelete,
    #                   sectionSign (ISO keyboards only, european keyboards only)
    # - Keypad special. keypadClear, keypadDecimalMark, keypadDivide, keypadEnter, keypadEqual,
    #                   keypadMinus, keypadMultiply, keypadPlus
    # - Arrows.         left, down, up, right

    # All possible modifiers: cmd, alt, ctrl, shift

    # All possible commands: https://nikitabobko.github.io/AeroSpace/commands

    alt-t = 'layout tiles horizontal vertical'
    alt-s = 'layout accordion horizontal vertical'

    alt-h = 'focus left'
    alt-j = 'focus down'
    alt-k = 'focus up'
    alt-l = 'focus right'

    alt-shift-h = 'move left'
    alt-shift-j = 'move down'
    alt-shift-k = 'move up'
    alt-shift-l = 'move right'

    alt-f = 'fullscreen'

    alt-minus = 'resize smart -50'
    alt-equal = 'resize smart +50'


    alt-1 = 'workspace 1'
    alt-2 = 'workspace 2'
    alt-3 = 'workspace 3'
    alt-4 = 'workspace 4'
    alt-5 = 'workspace 5'
    alt-6 = 'workspace 6'
    alt-7 = 'workspace 7'
    alt-8 = 'workspace 8'
    alt-9 = 'workspace 9'
    alt-0 = 'workspace 10'

    alt-shift-1 = 'move-node-to-workspace 1'
    alt-shift-2 = 'move-node-to-workspace 2'
    alt-shift-3 = 'move-node-to-workspace 3'
    alt-shift-4 = 'move-node-to-workspace 4'
    alt-shift-5 = 'move-node-to-workspace 5'
    alt-shift-6 = 'move-node-to-workspace 6'
    alt-shift-7 = 'move-node-to-workspace 7'
    alt-shift-8 = 'move-node-to-workspace 8'
    alt-shift-9 = 'move-node-to-workspace 9'
    alt-shift-0 = 'move-node-to-workspace 10'

    alt-tab = 'workspace-back-and-forth'
    alt-shift-tab = 'move-workspace-to-monitor --wrap-around next'

    # modes
    alt-shift-semicolon = 'mode service'
    alt-r = 'mode resize'
    alt-shift-backslash = 'mode join'

[mode.service.binding]
    shift-r = [
      'reload-config', 
      '''exec-and-forget
          terminal-notifier 
            -title "AeroSpace"
            -message "Config reloaded"
            -group aerospace.reload-config
            -remove aerospace.reload-config
            -ignoreDnD
      ''', 
      'mode main'
    ]
    r = ['flatten-workspace-tree', 'mode main'] # reset layout
    f = ['layout floating tiling', 'mode main'] # Toggle between floating and tiling layout
    # sticky is not yet supported https://github.com/nikitabobko/AeroSpace/issues/2
    #s = ['layout sticky tiling', 'mode main']

[mode.resize.binding]
    h = 'resize width -50'
    j = 'resize height +50'
    k = 'resize height -50'
    l = 'resize width +50'
    esc = ['mode main']

[mode.join.binding]
    h = ['join-with left', 'mode main']
    j = ['join-with down', 'mode main']
    k = ['join-with up', 'mode main']
    l = ['join-with right', 'mode main']

[[on-window-detected]]
if.app-id = 'com.mitchellh.ghostty'
run = 'move-node-to-workspace 1'

[[on-window-detected]]
if.app-id = 'com.google.Chrome'
if.window-title-regex-substring = '.*Google Chrome - Work$'
run = 'move-node-to-workspace 2'

[[on-window-detected]]
if.app-id = "com.google.Chrome"
if.window-title-regex-substring = '.* - Google Chrome - .* .Personal.$'
run = "move-node-to-workspace 3"

[[on-window-detected]]
if.app-id = 'com.apple.mail'
run = 'move-node-to-workspace 7'

[[on-window-detected]]
if.app-id = 'com.apple.iCal'
run = 'move-node-to-workspace 7'

[[on-window-detected]]
if.app-id = 'org.whispersystems.signal-desktop'
run = 'move-node-to-workspace 8'

[[on-window-detected]]
if.app-id = 'im.riot.app'
run = 'move-node-to-workspace 8'

[[on-window-detected]]
if.app-id = 'com.spotify.client'
run = 'move-node-to-workspace 6'

[[on-window-detected]]
if.app-id = 'com.bitwarden.desktop'
run = 'move-node-to-workspace 6'

[[on-window-detected]]
if.app-id = 'com.openai.chat'
run = 'move-node-to-workspace 5'

[[on-window-detected]]
if.app-id = 'md.obsidian'
run = 'move-node-to-workspace 4'

[[on-window-detected]]
if.app-id = 'com.todoist.mac.Todoist'
run = 'move-node-to-workspace 4'

[[on-window-detected]]
if.app-id = 'com.utmapp.UTM'
check-further-callbacks = true
run = 'move-node-to-workspace 9'

[[on-window-detected]]
if.app-id = 'com.utmapp.UTM'
if.window-title-regex-substring = '^macOS$'
run = 'move-node-to-workspace 10'
