require('user.plugin_configs.lualine')
require('user.plugin_configs.neo-tree')
require('user.plugin_configs.telescope')
require('user.plugin_configs.treesitter')
require('user.plugin_configs.autopairs')
require('user.plugin_configs.illuminate')
require('user.plugin_configs.comment')
require('user.plugin_configs.gitsigns')
require('user.plugin_configs.bufferline')
require('user.plugin_configs.nvim-surround')
require('user.plugin_configs.lsp')
require('user.plugin_configs.lsp_progress')
require('user.plugin_configs.fidget')
require('user.plugin_configs.cmp')
require('user.plugin_configs.null-ls')
require('user.plugin_configs.projects')
require('user.plugin_configs.ufo')
require('user.plugin_configs.harpoon')
require('user.plugin_configs.profile')
-- require('user.plugin_configs.auto-session')
-- require('user.plugin_configs.codeium')
require('user.plugin_configs.neogit')
