require('user.plugin_configs.lualine')
require('user.plugin_configs.cmp')
require('user.plugin_configs.nvim-tree')
require('user.plugin_configs.telescope')
require('user.plugin_configs.treesitter')
require('user.plugin_configs.autopairs')
require('user.plugin_configs.comment')
require('user.plugin_configs.gitsigns')
require('user.plugin_configs.bufferline')
require('user.plugin_configs.nvim-surround')
require('user.plugin_configs.lsp')
--[[ require('user.plugin_configs.lsp') ]]
